BiblioWeb/Controllers/HomeController.cs
using BiblioWeb.Clases;
using BiblioWeb.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BiblioWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IWebHostEnvironment hostEnvironment;

        public HomeController(ILogger<HomeController> logger, IWebHostEnvironment hostEnvironment)
        {
            _logger = logger;
            this.hostEnvironment = hostEnvironment;
        }
        [HttpGet]
        [Authorize(Roles = "Usuario")]
        public IActionResult Ventas(int id) {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View(new UsuariosCLS().MostrarUnLibro(id));
        }
        [HttpPost]
        [Authorize(Roles = "Usuario")]
        public IActionResult Ventas(string id) {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            new UsuariosCLS().RegistrarPedido(int.Parse(id));
            return RedirectToAction("Carrito","Home");
        }
        [HttpGet]
        public IActionResult Login() { 
            return View();
        }   
        [HttpPost]
        public async Task<IActionResult> Login(TbUsuario user)
        {
            string mensaje = new UsuariosCLS().Iniciar_Sesion(user);
            if (mensaje != "Correcto") {
                return View();
            }
            var claims = new List<Claim>
                    {
                        new Claim("Usuario", user.Correo),
                        new Claim("Contraseña", user.Contraseña),

                    };

            claims.Add(new Claim(ClaimTypes.Role, "Usuario"));

            var claimsIdentityAdmin = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentityAdmin));
            return RedirectToAction("Menu");
            
        }
        public async Task<IActionResult> Logout() {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
        [HttpGet]
        public IActionResult Registrar() {
            ViewBag.Error = "";
            return View();
        }
        [HttpPost]
        public IActionResult Registrar(TbUsuario user,TbCliente cliente) {
            ViewBag.Error = new UsuariosCLS().Registrar(user, cliente);
            return RedirectToAction("Login");
        }
        [HttpGet]
        [Authorize(Roles = "Usuario")]
        public IActionResult Carrito() {
            ViewBag.Precio = new UsuariosCLS().PrecioTotal();
            ViewBag.ListaID = new UsuariosCLS().GetIdPedido();
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View(new UsuariosCLS().MostrarPedidos());
        }
        [HttpPost]
        [Authorize(Roles = "Usuario")]
        public IActionResult Eliminar(int idEliminarPedido) {
            new UsuariosCLS().EliminarPedido(idEliminarPedido);
            return RedirectToAction("Carrito");
        }
        [HttpPost]
        [Authorize(Roles = "Usuario")]
        public IActionResult Compra() {
            
            return RedirectToAction("Ticket");
        }
        [HttpGet]
        [Authorize(Roles = "Usuario")]
        public IActionResult Menu() {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View(new UsuariosCLS().MostrarLibros());
        }
        [HttpPost]
        [Authorize(Roles = "Usuario")]
        public IActionResult Menu(string palabraClave)
        {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View(new UsuariosCLS().Filtro(palabraClave));
        }
        [HttpGet]
        [Authorize(Roles = "Usuario")]
        public IActionResult Vender() {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Usuario")]
        public IActionResult Vender(TbLibro librio, IFormFile image) {
            string wwwRootPath = hostEnvironment.WebRootPath;
            string extension = Path.GetExtension(image.FileName);
            string fileName = DateTime.Now.ToString("yymmssfff");
            string path = Path.Combine(wwwRootPath + "/img/", fileName + extension);
            string ruta = "/img/" + fileName + extension;
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                image.CopyTo(fileStream);
            }
            new UsuariosCLS().AgregarLibro(librio, ruta);
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View();
        }        
        [HttpGet]
        [Authorize(Roles = "Usuario")]
        public IActionResult UserConfig() {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            return View(new UsuariosCLS().infoCliente());
        }
        [Authorize(Roles = "Usuario")]
        public IActionResult Ticket() {
            UsuariosCLS obj = new UsuariosCLS();
            obj.Comprar();
            List<TicketCLS> list = obj.Ticket();
            if (list.Count != 0)
            {              
                ViewBag.Ticket = list[0].Total;
                ViewBag.Nombre = list[0].Nombre;
                ViewBag.Fecha = list[0].Fecha;
                return View(list); 
            }
            return RedirectToAction("Carrito");
        }
        [HttpPost]
        [Authorize(Roles = "Usuario")]
        public IActionResult UserConfig(TbCliente cliente, TbUsuario usuario)
        {
            ViewBag.Usuario = new UsuariosCLS().Usuario;
            new UsuariosCLS().ModificarCLiente(cliente, usuario);
            return View(new UsuariosCLS().infoCliente());
        }
    }
}

BiblioWeb/Controllers/StaticController.cs
using Microsoft.AspNetCore.Mvc;

namespace BiblioWeb.Controllers
{
    public class StaticController : Controller
    {
        public IActionResult Introduccion()
        {
            return View();
        }
        public IActionResult Nosotros() { 
            return View();
        }
        public IActionResult Agradecimientos() {
            return View();
        }
    }
}

BiblioWeb/Views/Home/Carrito.cshtml
@model List<TbLibro>
@{
    Layout = null;
    int i = 0;
}

<!DOCTYPE html>
<html lang="esp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BIBLIOWEB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link rel="stylesheet" href="~/css/project.css">
    <script src="https://kit.fontawesome.com/2c36e9b7b1.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://kit.fontawesome.com/2c36e9b7b1.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>        
    <nav>
        <input type="checkbox" id="check">
        <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
        </label>
        <label class="logo">BIBLIOWEB</label>
        <ul>
            <li><a asp-action="Menu" class=" text-decoration-none navA"><ion-icon name="grid"></ion-icon>Inicio</a></li>
                    <li><a asp-action="Carrito" class="active text-decoration-none navA"><ion-icon name="cart"></ion-icon>Carrito</a></li>
                    <li><a asp-action="Vender" class="text-decoration-none navA"><ion-icon name="pricetags"></ion-icon>Vender</a></li>
                    <li><a asp-action="UserConfig" class="text-decoration-none navA"><ion-icon name="person"></ion-icon>@ViewBag.Usuario</a></li>
                    <li><a asp-action="Logout" class="text-decoration-none navA"><ion-icon name="exit"></ion-icon>Salir Sesion</a></li>
        </ul>
    </nav>
    <br>
    <h2><ion-icon name="cart"></ion-icon>   Carrito</h2>
    <hr><br>
    <div class="page-container">
    @if (Model.Count != 0)
    {
                @foreach (var item in Model)
        {                        
            <a  class="product-container text-decoration-none">
                <img src="@item.Ruta">
                <h3>@item.Titulo</h3>
                <h2>@item.Autor</h2>
                <h4>@item.Genero</h4>
                <h2>@item.Precio</h2>   
                <input class="btn btn-danger" onclick="Elimanar(@ViewBag.ListaID[i])" type="button" value="Eliminar" id="Eliminar"/>
            </a>
            i++;
        }    
    }else
    {
            <h2>
                Lo sentimos aun no has agregado ningun libro a tu carrito :(.
            </h2>
    }
    </div>
    <hr><br>
    <div class="carrito">
        <div class="buttonCarrito">
            @if (@ViewBag.Precio != "$0")
            {
                <h2><ion-icon name="card"></ion-icon>Total a Pagar: @ViewBag.Precio</h2>
            }
            <form asp-action="Compra" asp-controller="Home" method="post">
                <button onclick="Comprar()" type="submit" class="preButton"><ion-icon name="logo-paypal"></ion-icon> PAGAR</button>
            </form>
        </div>
    </div>          
    <form asp-action="Eliminar"  asp-controller="Home" id="frmEliminar">
        <input type="hidden" id="idEliminarPedido" name="idEliminarPedido" />
    </form>
    <script>
        function Elimanar(id){            
            document.getElementById("idEliminarPedido").value = id;            
            frmEliminar.submit();
        }
        function Comprar() {
            var art = document.getElementById("Eliminar").value;

            if (art == 0) {
                swal("Sin articulos", "Añade articulos a tu carrito", "error");
            } else {
                swal("EXITO", "Compra en Proceso", "success");
            }
        }
    </script>
</body>
</html>

BiblioWeb/Views/Home/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="esp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BiblioWeb</title>
    <link rel="stylesheet" href="~/css/project.css">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>
    <section id="dividida">
        <div class="derecha">
            <form asp-action="Login" asp-controller="Home" method="post" class="login" id="frmLogin">
                <ion-icon name="book"></ion-icon>BiblioWeb
                <br><br>
                <h2>Inicia Sesion</h2>
                <hr><br>
                <h4><ion-icon name="mail"></ion-icon>e-mail:</h4>
                <input type="email" name="Correo" id="email" placeholder="correo electronico"  class="preInput">
                <br><br>
                <h4><ion-icon name="lock-closed"></ion-icon>Contraseña:</h4>
                <input type="password" name="Contraseña" id="contra" placeholder="contraseña"  class="preInput">
                <br><br><br>
                <button type="button"  class="preButton" onclick="Login()">INICIAR</button>
            </form>
        </div>
        <div class="izquierda">
            <form asp-action="Registrar" asp-controller="Home" method="get" class="login">
                <br><br><br>
                <h2>Registrate</h2>
                <hr><br>
                Registrate para poder disfrutar de todo lo que te ofrece
                <br>
                BiblioWeb
                <br><br><br><br>
                <button type="submit" class="preButton" >REGISTRARSE</button>                               
            </form>
        </div>
    </section>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function Login() {
            var mail = document.getElementById("email").value;
            var passw = document.getElementById("contra").value;

            var gmail = (mail.substr(-9));
            if (mail == "") {
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            } else if (passw == "") {
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            } else if (!(gmail == "gmail.com")) {
                swal("Correo No Valido", "Asegurate de que pusiste un correo valido: terminacion gmail.com", "error");
            } else { 
                frmLogin.submit();
            }    
        }
    </script>
</body>
</html>

BiblioWeb/Views/Home/Menu.cshtml
@model List<TbLibro>
@{
    Layout = null;    
}

<!DOCTYPE html>
<html lang="esp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BIBLIOWEB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/project.css">
    <script src="https://kit.fontawesome.com/2c36e9b7b1.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://kit.fontawesome.com/2c36e9b7b1.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

<!--BARRA DE NAVEGACION-->   
<nav>
    <input type="checkbox" id="check">
    <label for="check" class="checkbtn">
        <i class="fas fa-bars"></i>
    </label>
    <label class="logo"><ion-icon name="book"></ion-icon>BiblioWeb</label>
    <ul>
        <li><a asp-action="Menu" class="active text-decoration-none navA"><ion-icon name="grid"></ion-icon>Inicio</a></li>
        <li><a asp-action="Carrito" class="text-decoration-none navA"><ion-icon name="cart"></ion-icon>Carrito</a></li>
        <li><a asp-action="Vender" class="text-decoration-none navA"><ion-icon name="pricetags"></ion-icon>Vender</a></li>
        <li><a asp-action="UserConfig" class="text-decoration-none navA"><ion-icon name="person"></ion-icon>@ViewBag.Usuario</a></li>
        <li><a asp-action="Logout" class="text-decoration-none navA"><ion-icon name="exit"></ion-icon>Salir Sesion</a></li>
    </ul>
</nav>

<!--CARRUSEL DE IMAGENES-->
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" cursive-current="true" cursive-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" cursive-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" cursive-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" cursive-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <a href="/img/AVANCE 2 PA BIBLIOWEB.docx.pdf"><img src="~/img/bgQR.jpg" class="d-block w-100" alt="banIntr"></a>
        </div>
        <div class="carousel-item">
            <a asp-action="Introduccion" asp-controller="Static"><img src="~/img/bgIntroduction.png" class="d-block w-100" alt="banIntr"></a>
        </div>
        <div class="carousel-item">
            <a asp-action="Nosotros" asp-controller="Static"><img src="~/img/bgNosotros.png" class="d-block w-100" alt="banNos"></a>
        </div>
        <div class="carousel-item">
            <a asp-action="Agradecimientos" asp-controller="Static"><img src="~/img/bgAgr.png" class="d-block w-100" alt="banAgr"></a>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" cursive-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" cursive-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>    
    <br><br><br>
<!--PAGINA-->
<div class="container">
    <div class="row">        
        <form class="d-flex" asp-action="Menu" asp-controller="Home" method="post">
            <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Buscar" name="palabraClave">
            <button class="btn btn-outline-primary" type="submit">Buscar</button>
        </form>        
    </div>
</div>
    <div class="page-container">
    @if (Model != null)
    {
        @foreach (var item in Model)
        {                        
            <a href="@Url.Action("Ventas","Home",new {id = @item.IdLibro})" class="product-container text-decoration-none">
                <img src="@item.Ruta">
                <h3>@item.Titulo</h3>
                <h2>@item.Autor</h2>
                <h4>@item.Genero</h4>
                <h2>@item.Precio</h2>                    
                @*@Html.ActionLink("Comprar","Ventas","Home",new { id = @item.IdLibro},new {@class="btn btn-dark"})                *@
            </a>
        }          
    } else
    {
        <h2>Lo sentimos, no pudimos encontrar este libro :(</h2>
    }
    </div>
    <br><br><br>
    <script src="~/js/popperjs.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>

BiblioWeb/Views/Home/Registrar.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="esp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BiblioWeb</title>
    <link rel="stylesheet" href="~/css/project.css">    
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    
</head>
<body>
    <section class="registerContainer">
        <form asp-action="Registrar" asp-controller="Home" method="post" class="register" id="frmRegistrar">
            <ion-icon name="book"></ion-icon>BiblioWeb
            <br><br>
            <h2>Registro</h2>
            <hr>
            <br><br>
            <h4><ion-icon name="person"></ion-icon>Nombre: </h4>
            <input type="text" name="Nombre" id="nombre" placeholder="nombre" class="preInput">
            <br><br>
            <h4><ion-icon name="bookmark"></ion-icon>Apellido Paterno: </h4>
            <input type="text" name="ApellidoPat" id="apellidoP" placeholder="apellidoP" class="preInput">
            <br><br>
            <h4><ion-icon name="bookmarks"></ion-icon>Apellido Materno: </h4>
            <input type="text" name="ApellidoMat" id="apellidoM" placeholder="apellidoM"  class="preInput">
            <br><br>
            <h4><ion-icon name="paper-plane"></ion-icon>Colonia: </h4>
            <input type="text" name="Colonia" id="colonia" placeholder="colonia"  class="preInput">
            <br><br>
            <h4><ion-icon name="car"></ion-icon>Calle: </h4>
            <input type="text" name="Calle" id="calle" placeholder="calle"  class="preInput">
            <br><br>
            <h4><ion-icon name="clipboard"></ion-icon>Numero: </h4>
            <input type="text" name="Numero" id="numero" placeholder="numero"  class="preInput">
            <br><br>
            <h4><ion-icon name="mail"></ion-icon>e-mail: </h4>
            <input type="email" name="Correo" id="email" placeholder="correo electronico"  class="preInput">
            <br><br>
            <h4><ion-icon name="lock-closed"></ion-icon>Contraseña: </h4>
            <input type="password" name="Contraseña" id="contra" placeholder="contraseña"  class="preInput">
            <br><br>
            <h4><ion-icon name="document-lock"></ion-icon>Confirmar: </h4>
            <input type="password" name="contraConf" id="contraConf" placeholder="contraseña"  class="preInput">
            <br><br><br>
            <button type="button" class="preButton" id="open-popup-btn" onclick="Registro()">INICIAR</button>
            <br><br><br>
        </form>
    </section>    
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function Registro() {
            var name = document.getElementById("nombre").value;
            var apP = document.getElementById("apellidoP").value;
            var apM = document.getElementById("apellidoM").value;
            var col = document.getElementById("colonia").value;
            var street = document.getElementById("calle").value;
            var num = document.getElementById("numero").value;
            var mail = document.getElementById("email").value;
            var pd = document.getElementById("contra").value;
            var pdC = document.getElementById("contraConf").value;

            var gmail = (mail.substr(-9));

            if (name == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if(apP == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if (apM == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if (col == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if (street == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if (num == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if (mail == ""){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if (!(gmail == "gmail.com")){
                swal("Correo No Valido", "Asegurate de que pusiste un correo valido: terminacion gmail.com", "error");
            }else if((pd == "")){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if((pdC == "")){
                swal("Campos Faltantes", "Asegurate de que los campos esten llenos", "error");
            }else if(pd == document.getElementById("contraConf").value){    
                frmRegistrar.submit();
            }
            else{
                swal("Contraseñas Distintas", "Asegurate de que las contraseñas coincidan", "error");
            }
        }
    </script>
</body>
</html>

BiblioWeb/Views/Home/Ticket.cshtml
@using BiblioWeb.Clases
@model List<TicketCLS>
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket</title>
    <link rel="stylesheet" href="~/css/StyleSheet.css">
</head>
<body>
    <header>
        <h1>
            BiblioWeb
        </h1>
        
    </header>
    <hr/>
    <main>
        <section>
            <div class="container">
                <div class="row">
                    <h2>Nombre: @ViewBag.Nombre</h2>
                    <span class="span">Fecha: @ViewBag.Fecha</span>
                    <br>  
                </div>
            </div>
            <article class="table-wrapper">  
        
                <table class="fl-table">
                    <thead>
                        <tr>
                            <th>
                                Titulo
                            </th>                            
                            <th>
                                Autor
                            </th>
                            <th>
                                Genero
                            </th>
                            <th>
                                Precio
                            </th>                         
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                       {
                            <tr>
                                 <th>
                                     @item.Titulo
                                 </th>
                                 <th>
                                     @item.Autor
                                 </th>
                                 <th>
                                     @item.Genero
                                 </th>
                                 <th>
                                     @item.Precio
                                 </th>

                            </tr>
                       }
                        <tr>
                            <th colspan="3">Total</th>                            
                            <th>@ViewBag.Ticket</th>
                        </tr>
                    </tbody>
                </table>
            </article>
        </section>
    </main>
</body>
</html>

<script>
    window.onload = function() {
        if (window.print) { 
          window.print();
        }
    }
</script>